// Do not edit directly
// Generated with design-token-editor on 2023/8/1 11:19:16

export default {
    // 按钮加载遮罩
    T_BUTTON_COMMON_COLOR_MASK: '#ffffff',
    // 按钮/主/背景色
    T_BUTTON_PRIMARY_COLOR_BG_DEFAULT: 'linear-gradient(135deg, #6488fc 0%,#3860f4 100%)',
    // 按钮/主/背景色/hover
    T_BUTTON_PRIMARY_COLOR_BG_HOVER: 'linear-gradient(135deg, #5c76e8 0%,#3357df 100%)',
    // 按钮/主/文本色
    T_BUTTON_PRIMARY_COLOR_TEXT_DEFAULT: '#ffffff',
    // 按钮/次/背景色
    T_BUTTON_SECONDARY_COLOR_BG_DEFAULT: '#ffffff',
    // 卡片/背景色
    T_CARD_COLOR_BG_DEFAULT: '#ffffff',
    // 图表/时间范围选择器/背景色
    T_CHART_TIMEPICKER_BG_DEFAULT: '#EAEEFD',
    // 图表/时间范围选择器/icon
    T_CHART_TIMEPICKER_ICON_DEFAULT: '#6488fc',
    // 背景/渐变/内容区
    T_COLOR_BG_CONTENT_1: 'linear-gradient(180deg, #ebedf5 0%, #ebedf5 100%)',
    // 背景/常规/亮色
    T_COLOR_BG_DEFAULT_BRIGHT: '#ffffff',
    // 背景/常规/深色
    T_COLOR_BG_DEFAULT_DARK: '#f6f6fb',
    // 背景/常规/hover
    T_COLOR_BG_DEFAULT_HOVER: '#e3e9ff',
    // 背景/常规/浅色
    T_COLOR_BG_DEFAULT_LIGHT: '#fafafc',
    // 背景/常规/默认色，替换为T_COLOR_BG_DEFAULT_BRIGHT
    T_COLOR_BG_DEFAULT_NORMAL: '#ffffff',
    // 背景/禁用状态/深色
    T_COLOR_BG_DISABLED_DARK: '#cccccc',
    // 背景/禁用状态/浅色
    T_COLOR_BG_DISABLED_LIGHT: '#f7f7f7',
    // 背景/错误状态/深色
    T_COLOR_BG_ERROR_DARK: '#f44336',
    // 背景/错误状态/浅色
    T_COLOR_BG_ERROR_LIGHT: '#fff0f0',
    // 背景/高亮
    T_COLOR_BG_HIGHLIGHT: '#fff5bd',
    // 背景/菜单
    T_COLOR_BG_MENU: '#ffffff',
    // 背景/提示状态/深色
    T_COLOR_BG_NOTICE_DARK: '#526075',
    // 背景/提示状态/浅色
    T_COLOR_BG_NOTICE_LIGHT: '#fafafc',
    // 背景/纯色/品牌色1
    T_COLOR_BG_PRIMARY_1: '#3860f4',
    // 背景/纯色/品牌色2
    T_COLOR_BG_PRIMARY_2: '#3357df',
    // 背景/渐变/品牌色3
    T_COLOR_BG_PRIMARY_3: 'linear-gradient(135deg, #6488fc 0%,#3860f4 100%)',
    // 背景/渐变/品牌色4
    T_COLOR_BG_PRIMARY_4: 'linear-gradient(135deg, #5c76e8 0%,#3357df 100%)',
    // 背景/浅色/品牌色5
    T_COLOR_BG_PRIMARY_5: '#f8f8ff',
    // 背景/侧边栏
    T_COLOR_BG_SIDEBAR: '#e7e9f3',
    // 背景/成功状态/深色
    T_COLOR_BG_SUCCESS_DARK: '#15AD31',
    // 背景/成功状态/浅色
    T_COLOR_BG_SUCCESS_LIGHT: '#E6FFED',
    // 背景/透明
    T_COLOR_BG_TRANSPARENT: 'transparent',
    // 背景/警告状态/深色
    T_COLOR_BG_WARNING_DARK: '#ffc42e',
    // 背景/警告状态/浅色
    T_COLOR_BG_WARNING_LIGHT: '#fffce6',
    // 背景/白色，替换为T_COLOR_BG_DEFAULT_BRIGHT
    T_COLOR_BG_WHITE: '#ffffff',
    // 图例/蓝-1
    T_COLOR_LEGEND_BLUE_1: '#e7eefd',
    // 图例/蓝-2
    T_COLOR_LEGEND_BLUE_2: '#c1d4fa',
    // 图例/蓝-3
    T_COLOR_LEGEND_BLUE_3: '#95bff7',
    // 图例/蓝-4
    T_COLOR_LEGEND_BLUE_4: '#6ca7f4',
    // 图例/蓝-5
    T_COLOR_LEGEND_BLUE_5: '#4f95f2',
    // 图例/蓝-6
    T_COLOR_LEGEND_BLUE_6: '#3c90f0',
    // 图例/蓝-7
    T_COLOR_LEGEND_BLUE_7: '#1971cb',
    // 图例/蓝-8
    T_COLOR_LEGEND_BLUE_8: '#0c5fa7',
    // 图例/蓝-9
    T_COLOR_LEGEND_BLUE_9: '#152d4f',
    // 图例/青-1
    T_COLOR_LEGEND_CYAN_1: '#e8fcfc',
    // 图例/青-2
    T_COLOR_LEGEND_CYAN_2: '#c3f8f5',
    // 图例/青-3
    T_COLOR_LEGEND_CYAN_3: '#98f3e5',
    // 图例/青-4
    T_COLOR_LEGEND_CYAN_4: '#70efdb',
    // 图例/青-5
    T_COLOR_LEGEND_CYAN_5: '#55ecd6',
    // 图例/青-6
    T_COLOR_LEGEND_CYAN_6: '#43eacb',
    // 图例/青-7
    T_COLOR_LEGEND_CYAN_7: '#1fc4a1',
    // 图例/青-8
    T_COLOR_LEGEND_CYAN_8: '#12a17d',
    // 图例/青-9
    T_COLOR_LEGEND_CYAN_9: '#174d45',
    // 图例/绿-1
    T_COLOR_LEGEND_GREEN_1: '#E6FFED',
    // 图例/绿-2
    T_COLOR_LEGEND_GREEN_2: '#C2FFC9',
    // 图例/绿-3
    T_COLOR_LEGEND_GREEN_3: '#9EFFA5',
    // 图例/绿-4
    T_COLOR_LEGEND_GREEN_4: '#70E47E',
    // 图例/绿-5
    T_COLOR_LEGEND_GREEN_5: '#43C858',
    // 图例/绿-6
    T_COLOR_LEGEND_GREEN_6: '#15AD31',
    // 图例/绿-7
    T_COLOR_LEGEND_GREEN_7: '#0E912A',
    // 图例/绿-8
    T_COLOR_LEGEND_GREEN_8: '#077523',
    // 图例/绿-9
    T_COLOR_LEGEND_GREEN_9: '#00591C',
    // 图例/浅蓝-1
    T_COLOR_LEGEND_LIGHTBLUE_1: '#e7f5fd',
    // 图例/浅蓝-2
    T_COLOR_LEGEND_LIGHTBLUE_2: '#c1e9fb',
    // 图例/浅蓝-3
    T_COLOR_LEGEND_LIGHTBLUE_3: '#93e2f8',
    // 图例/浅蓝-4
    T_COLOR_LEGEND_LIGHTBLUE_4: '#6ad7f5',
    // 图例/浅蓝-5
    T_COLOR_LEGEND_LIGHTBLUE_5: '#4dcff4',
    // 图例/浅蓝-6
    T_COLOR_LEGEND_LIGHTBLUE_6: '#3ad0f3',
    // 图例/浅蓝-7
    T_COLOR_LEGEND_LIGHTBLUE_7: '#17b1cd',
    // 图例/浅蓝-8
    T_COLOR_LEGEND_LIGHTBLUE_8: '#0a95a8',
    // 图例/浅蓝-9
    T_COLOR_LEGEND_LIGHTBLUE_9: '#154250',
    // 图例/橙-1
    T_COLOR_LEGEND_ORANGE_1: '#fff5e6',
    // 图例/橙-2
    T_COLOR_LEGEND_ORANGE_2: '#ffe3bd',
    // 图例/橙-3
    T_COLOR_LEGEND_ORANGE_3: '#ffc48d',
    // 图例/橙-4
    T_COLOR_LEGEND_ORANGE_4: '#ffac61',
    // 图例/橙-5
    T_COLOR_LEGEND_ORANGE_5: '#ff9e42',
    // 图例/橙-6
    T_COLOR_LEGEND_ORANGE_6: '#FF8C2E',
    // 图例/橙-7
    T_COLOR_LEGEND_ORANGE_7: '#d9610b',
    // 图例/橙-8
    T_COLOR_LEGEND_ORANGE_8: '#B34400',
    // 图例/橙-9
    T_COLOR_LEGEND_ORANGE_9: '#543211',
    // 图例/紫-1
    T_COLOR_LEGEND_PURPLE_1: '#f4ebf9',
    // 图例/紫-2
    T_COLOR_LEGEND_PURPLE_2: '#e1ccf0',
    // 图例/紫-3
    T_COLOR_LEGEND_PURPLE_3: '#c6a7e5',
    // 图例/紫-4
    T_COLOR_LEGEND_PURPLE_4: '#af85db',
    // 图例/紫-5
    T_COLOR_LEGEND_PURPLE_5: '#a06dd4',
    // 图例/紫-6
    T_COLOR_LEGEND_PURPLE_6: '#935ecf',
    // 图例/紫-7
    T_COLOR_LEGEND_PURPLE_7: '#6b3aaa',
    // 图例/紫-8
    T_COLOR_LEGEND_PURPLE_8: '#4f298a',
    // 图例/紫-9
    T_COLOR_LEGEND_PURPLE_9: '#322044',
    // 图例/红-1
    T_COLOR_LEGEND_RED_1: '#fff0f0',
    // 图例/红-2
    T_COLOR_LEGEND_RED_2: '#ffe2e2',
    // 图例/红-3
    T_COLOR_LEGEND_RED_3: '#fed4d4',
    // 图例/红-4
    T_COLOR_LEGEND_RED_4: '#FBA49F',
    // 图例/红-5
    T_COLOR_LEGEND_RED_5: '#F7736B',
    // 图例/红-6
    T_COLOR_LEGEND_RED_6: '#f44336',
    // 图例/红-7
    T_COLOR_LEGEND_RED_7: '#C13126',
    // 图例/红-8
    T_COLOR_LEGEND_RED_8: '#8D1E16',
    // 图例/红-9
    T_COLOR_LEGEND_RED_9: '#5a0c06',
    // 图例/黄-1
    T_COLOR_LEGEND_YELLOW_1: '#fffce6',
    // 图例/黄-2
    T_COLOR_LEGEND_YELLOW_2: '#fff5bd',
    // 图例/黄-3
    T_COLOR_LEGEND_YELLOW_3: '#ffe38d',
    // 图例/黄-4
    T_COLOR_LEGEND_YELLOW_4: '#FFD761',
    // 图例/黄-5
    T_COLOR_LEGEND_YELLOW_5: '#ffd042',
    // 图例/黄-6
    T_COLOR_LEGEND_YELLOW_6: '#ffc42e',
    // 图例/黄-7
    T_COLOR_LEGEND_YELLOW_7: '#d9980b',
    // 图例/黄-8
    T_COLOR_LEGEND_YELLOW_8: '#b37400',
    // 图例/黄-9
    T_COLOR_LEGEND_YELLOW_9: '#544411',
    // 线条/常规/深色
    T_COLOR_LINE_DEFAULT_DARK: '#c3cad9',
    // 线条/常规/浅色
    T_COLOR_LINE_DEFAULT_LIGHT: '#d2d6ea',
    // 线条/常规/透明
    T_COLOR_LINE_DEFAULT_TRANSPARENT: 'transparent',
    // 线条/禁用/深色
    T_COLOR_LINE_DISABLED_DARK: '#cccccc',
    // 线条/禁用/浅色
    T_COLOR_LINE_DISABLED_LIGHT: '#d9d9d9',
    // 线条/错误/深色
    T_COLOR_LINE_ERROR_DARK: '#f44336',
    // 线条/错误/浅色
    T_COLOR_LINE_ERROR_LIGHT: '#fed4d4',
    // 线条/提示/深色
    T_COLOR_LINE_NOTICE_DARK: '#526075',
    // 线条/提示/浅色
    T_COLOR_LINE_NOTICE_LIGHT: '#d2d6ea',
    // 线条/主色
    T_COLOR_LINE_PRIMARY_DEFAULT: '#3860f4',
    // 线条/主色/hover
    T_COLOR_LINE_PRIMARY_HOVER: '#3357df',
    // 线条/浅色
    T_COLOR_LINE_PRIMARY_LIGHT: '#e3e9ff',
    // 线条/正确/深色
    T_COLOR_LINE_SUCCESS_DARK: '#15AD31',
    // 线条/正确/浅色
    T_COLOR_LINE_SUCCESS_LIGHT: '#9EFFA5',
    // 线条/警告/深色
    T_COLOR_LINE_WARNING_DARK: '#ffc42e',
    // 线条/警告/浅色
    T_COLOR_LINE_WARNING_LIGHT: '#ffe38d',
    // 文本/常规/亮色
    T_COLOR_TEXT_DEFAULT_BRIGHT: '#ffffff',
    // 文本/常规/深色
    T_COLOR_TEXT_DEFAULT_DARK: '#0a1633',
    // 文本/常规/浅色
    T_COLOR_TEXT_DEFAULT_LIGHT: '#526075',
    // 文本/常规/默认色，替换为T_COLOR_TEXT_DEFAULT_BRIGHT
    T_COLOR_TEXT_DEFAULT_NORMAL: '#ffffff',
    // 文本/禁用
    T_COLOR_TEXT_DISABLED: '#cccccc',
    // 文本/错误
    T_COLOR_TEXT_ERROR: '#f44336',
    // 文本/错误/深色
    T_COLOR_TEXT_ERROR_DARK: '#5a0c06',
    // 文本/主色
    T_COLOR_TEXT_PRIMARY_DEFAULT: '#3860f4',
    // 文本/主色/hover
    T_COLOR_TEXT_PRIMARY_HOVER: '#3357df',
    // 文本/备注/深色
    T_COLOR_TEXT_REMARK_DARK: '#7a8baa',
    // 文本/备注/浅色
    T_COLOR_TEXT_REMARK_LIGHT: 'rgba(10,22,51,0.2)',
    // 文本/正确
    T_COLOR_TEXT_SUCCESS: '#15AD31',
    // 文本/正确/深色
    T_COLOR_TEXT_SUCCESS_DARK: '#00591C',
    // 系统黑色文本
    T_COLOR_TEXT_SYSTEM_BLACK: '#000000',
    // 系统白色文本
    T_COLOR_TEXT_SYSTEM_WHITE: '#ffffff',
    // 文本/警告
    T_COLOR_TEXT_WARNING: '#ffc42e',
    // 文本/警告/深色
    T_COLOR_TEXT_WARNING_DARK: '#544411',
    // 文本/白色，替换为T_COLOR_TEXT_DEFAULT_BRIGHT
    T_COLOR_TEXT_WHITE: '#ffffff',
    // 大号控件字号
    T_CONTROL_FONT_SIZE_LG: '12px',
    // 中号控件字号
    T_CONTROL_FONT_SIZE_MD: '12px',
    // 小号控件字号
    T_CONTROL_FONT_SIZE_SM: '12px',
    // 大号控件高度
    T_CONTROL_HEIGHT_LG: '32px',
    // 中号控件高度
    T_CONTROL_HEIGHT_MD: '28px',
    // 小号控件高度
    T_CONTROL_HEIGHT_SM: '24px',
    // 大号控件间距
    T_CONTROL_SPACING_LG: '8px',
    // 中号控件间距
    T_CONTROL_SPACING_MD: '8px',
    // 小号控件间距
    T_CONTROL_SPACING_SM: '8px',
    // 圆形
    T_CORNER_CIRCLE: '50%',
    // 大圆角，用于卡片圆角
    T_CORNER_LG: '4px',
    // 默认圆角，常用于按钮/输入框等
    T_CORNER_SM: '2px',
    // 直角
    T_CORNER_ZERO: '0',
    // 抽屉/操作/背景/默认
    T_DRAWER_RESIZER_BG_DEFAULT: 'rgba(0,0,0,0.3)',
    // 抽屉/操作/背景/悬停
    T_DRAWER_RESIZER_BG_HOVER: 'rgba(0,0,0,0.5)',
    // 表单项/垂直间距
    T_FORM_ITEM_SPACING_VERTICAL: '16px',
    // 顶部导航左侧LOGO背景色
    T_FRAME_LOGO_COLOR_BG_DEFAULT: '#3357df',
    // 全部产品列表/图标颜色
    T_FRAME_PRODUCTS_COLOR_TEXT_ICON: '#152d4f',
    // 全局左侧收藏栏选中的产品背景色
    T_FRAME_SIDEBAR_COLOR_BG_ACTIVE: '#f8f8ff',
    // 全局左侧收藏栏默认背景色
    T_FRAME_SIDEBAR_COLOR_BG_DEFAULT: '#dfe0f1',
    // 全局左侧收藏栏展开状态背景色
    T_FRAME_SIDEBAR_COLOR_BG_EXPAND: '#ffffff',
    // 顶部导航默认背景色
    T_FRAME_TOP_COLOR_BG_DEFAULT: '#3860f4',
    // 顶部导航hover背景色/Logo背景色
    T_FRAME_TOP_COLOR_BG_HOVER: '#3357df',
    // 大号控件高度
    T_HEIGHT_LG: '32px',
    // 中号控件高度
    T_HEIGHT_MD: '28px',
    // 小号控件高度
    T_HEIGHT_SM: '24px',
    // 代码编辑器/读写/背景色/操作
    T_IDE_DEFAULT_COLOR_BG_ACTION: 'rgba(255,255,255,0.12)',
    // 代码编辑器/读写/背景色/默认
    T_IDE_DEFAULT_COLOR_BG_DEFAULT: '#0a1633',
    // 代码编辑器/只读/背景色/操作
    T_IDE_READONLY_COLOR_BG_ACTION: 'rgba(10,22,51,0.12)',
    // 代码编辑器/只读/背景色/默认
    T_IDE_READONLY_COLOR_BG_DEFAULT: '#f6f6fb',
    // 输入框/背景色/激活
    T_INPUT_COLOR_BG_ACTIVE: '#f6f6fb',
    // 输入框/背景色/默认
    T_INPUT_COLOR_BG_DEFAULT: '#fafafc',
    // 输入框/背景色/高亮/默认
    T_INPUT_COLOR_BG_HL_DEFAULT: '#e3e9ff',
    // 输入框/背景色/高亮/错误
    T_INPUT_COLOR_BG_HL_ERROR: '#fed4d4',
    // 默认线条，实线
    T_LINE_STYLE_BASE: 'solid',
    // 虚线边框样式，用于添加/上传照片按钮
    T_LINE_STYLE_DASHED: 'dashed',
    // 默认线条高
    T_LINE_WIDTH_BASE: '1px',
    // 粗线条
    T_LINE_WIDTH_LG: '2px',
    // 无线条
    T_LINE_WIDTH_SM: '0px',
    // 加载底部蒙层
    T_LOADING_COLOR_LAYER_DEFAULT: 'rgba(255,255,255,0.7)',
    // 弹窗/蒙层
    T_MODAL_COLOR_LAYER_DEFAULT: 'rgba(0,0,0,0.5)',
    // 弹窗/阴影
    T_MODAL_SHADOW_DEFAULT:
        '0 3px 6px -4px rgba(0,0,0,0.12),0 6px 16px 0 rgba(0,0,0,0.08),0 9px 28px 8px rgba(0,0,0,0.05)',
    // 左侧订单模块背景
    T_PAY_COLOR_BG_1: 'linear-gradient(180deg, #ebedf5 0%, #ebedf5 100%)',
    // 右侧计费模块背景
    T_PAY_COLOR_BG_2: '#efeff8',
    // 左侧订单卡片下半段背景
    T_PAY_COLOR_BG_3: '#f8f8ff',
    // 弹出层/背景色/暗
    T_POPOVER_COLOR_BG_DARK: '#0a1633',
    // 弹出层/背景色/亮
    T_POPOVER_COLOR_BG_LIGHT: '#ffffff',
    // 弹出层/边框/暗
    T_POPOVER_COLOR_LINE_DARK: 'transparent',
    // 弹出层/边框/亮
    T_POPOVER_COLOR_LINE_LIGHT: '#d2d6ea',
    // 进度条/背景色
    T_PROGRESS_COLOR_BG_DEFAULT: '#dfe0f1',
    // 单选框/卡片标题/背景色/激活
    T_RADIO_CARD_COLOR_BG_ACTIVE: '#fafafc',
    // 滚动条/背景色
    T_SCROLLBAR_COLOR_BG_DEFAULT: 'rgba(0,0,0,0.12)',
    // 滚动条/边框色
    T_SCROLLBAR_COLOR_BORDER_DEFAULT: 'rgba(255,255,255,0.7)',
    // 块/下/大
    T_SHADOW_BLOCK_BOTTOM_LG:
        '0 46px 24px -35px rgba(0,0,0,0.05),0 25px 10px -16px rgba(0,0,0,0.05),0 10px 6px -6px rgba(0,0,0,0.05)',
    // 块/下/小
    T_SHADOW_BLOCK_BOTTOM_SM: '0 3px 3px -2px rgba(0,0,0,0.05),0 8px 6px -6px rgba(0,0,0,0.08)',
    // 块/常规/大
    T_SHADOW_BLOCK_DEFAULT_LG:
        '0 6px 16px 0 rgba(0,0,0,0.05), 0 16px 24px -8px rgba(0,0,0,0.08), 0 0 16px 0 rgba(0,0,0,0.05),inset 0 -2px 0px 0px rgba(0,0,0,0.08)',
    // 块/常规/中
    T_SHADOW_BLOCK_DEFAULT_MD:
        '0 0 1px 0 rgba(0,0,0,0.12), 0 8px 12px -4px rgba(0,0,0,0.12), 0 4px 4px -2px rgba(0,0,0,0.05),inset 0 -2px 0px 0px rgba(0,0,0,0.08)',
    // 块/常规/小
    T_SHADOW_BLOCK_DEFAULT_SM:
        '0 0 2px 0 rgba(0,0,0,0.08), 0 5px 8px -4px rgba(0,0,0,0.12), 0 1px 0 0 rgba(0,0,0,0.05),inset 0 -1px 0px 0px rgba(0,0,0,0.08)',
    // 块/左/大
    T_SHADOW_BLOCK_LEFT_LG:
        '-46px 0 24px -35px rgba(0,0,0,0.05),-25px 0 10px -16px rgba(0,0,0,0.05),-10px 0 6px -6px rgba(0,0,0,0.05)',
    // 块/左/小
    T_SHADOW_BLOCK_LEFT_SM: '-3px 0 3px -2px rgba(0,0,0,0.05),-8px 0 6px -6px rgba(0,0,0,0.08)',
    // 块/右/大
    T_SHADOW_BLOCK_RIGHT_LG:
        '46px 0 24px -35px rgba(0,0,0,0.05),25px 0 10px -16px rgba(0,0,0,0.05),10px 0 6px -6px rgba(0,0,0,0.05)',
    // 块/右/小
    T_SHADOW_BLOCK_RIGHT_SM: '3px 0 3px -2px rgba(0,0,0,0.05),8px 0 6px -6px rgba(0,0,0,0.08)',
    // 块/上/大
    T_SHADOW_BLOCK_TOP_LG:
        '0 -46px 24px -35px rgba(0,0,0,0.05),0 -25px 10px -16px rgba(0,0,0,0.05),0 -10px 6px -6px rgba(0,0,0,0.05)',
    // 块/上/小
    T_SHADOW_BLOCK_TOP_SM: '0 -3px 3px -2px rgba(0,0,0,0.05),0 -8px 6px -6px rgba(0,0,0,0.08)',
    // 按钮/白/默认
    T_SHADOW_BUTTON_DEFAULT: '0 2px 3px 0 rgba(0,0,0,0.12),inset 0 -2px 0 0 #e3e9ff',
    // 按钮/错误色/默认
    T_SHADOW_BUTTON_ERROR: '0 1px 3px -1px #f44336',
    // 按钮/错误色/hover
    T_SHADOW_BUTTON_ERROR_HOVER: '0 5px 8px -4px #f44336',
    // 按钮/白/hover
    T_SHADOW_BUTTON_HOVER:
        '0 0 1px 0 rgba(0,0,0,0.12),0 8px 12px -4px rgba(0,0,0,0.12),0 2px 1px -1px rgba(0,0,0,0.05), inset 0 -2px 0 0 #e3e9ff',
    // 按钮/品牌色/默认
    T_SHADOW_BUTTON_PRIMARY:
        '0 2px 4px -1px #5c76e8, inset 0 -3px 0 0 rgba(0,0,0,0.12), inset 0 1px 0 0 rgba(0,0,0,0.12)',
    // 按钮/品牌色/hover
    T_SHADOW_BUTTON_PRIMARY_HOVER:
        '0 5px 8px -4px #5c76e8, inset 0 -3px 0 0 rgba(0,0,0,0.12), inset 0 1px 0 0 rgba(0,0,0,0.12)',
    // 内阴影/输入框
    T_SHADOW_INSET_1: 'inset 0 1px 3px 0 #d2d6ea',
    // 内阴影/下
    T_SHADOW_INSET_BOTTOM: 'inset 0 -10px 8px -8px rgba(0,0,0,0.12)',
    // 内阴影/默认
    T_SHADOW_INSET_DEFAULT: 'inset 0 3px 0 0 rgba(0,0,0,0.05)',
    // 内阴影/错误
    T_SHADOW_INSET_ERROR: 'inset 0 1px 3px 0 #fed4d4',
    // 内阴影/左
    T_SHADOW_INSET_LEFT: 'inset 10px 0 8px -8px rgba(0,0,0,0.12)',
    // 内阴影/右
    T_SHADOW_INSET_RIGHT: 'inset -10px 0 8px -8px rgba(0,0,0,0.12)',
    // 内阴影/上
    T_SHADOW_INSET_TOP: 'inset 0 10px 8px -8px rgba(0,0,0,0.12)',
    // 骨架屏/背景色/深色
    T_SKELETON_COLOR_BG_DARK: '#efeff8',
    // 骨架屏/背景色/浅色
    T_SKELETON_COLOR_BG_LIGHT: '#f6f6fb',
    // 滑块/背景色/激活
    T_SLIDER_COLOR_BG_ACTIVE: '#f8f8ff',
    // 滑块/背景色/未激活
    T_SLIDER_COLOR_BG_DEFAULT: '#fafafc',
    // 滑块/边框色/激活
    T_SLIDER_COLOR_LINE_ACTIVE: '#3860f4',
    // 滑块/边框色/未激活
    T_SLIDER_COLOR_LINE_DEFAULT: '#c3cad9',
    // 滑块/文本色/激活
    T_SLIDER_COLOR_TEXT_ACTIVE: '#3860f4',
    // 滑块/文本色/未激活
    T_SLIDER_COLOR_TEXT_DEFAULT: '#7a8baa',
    // 弹窗内表单间纵向间距
    T_SPACING_COMMON_LG: '16px',
    // 大号按钮左右内间距/页面内按钮与按钮横向间距
    T_SPACING_COMMON_MD: '12px',
    // 中号按钮左右内间距/弹窗内按钮与按钮的横向间距
    T_SPACING_COMMON_SM: '8px',
    //
    T_SPACING_COMMON_XLG: '20px',
    // icon和文本之间的间距
    T_SPACING_COMMON_XS: '4px',
    // 页面内表单间纵向间距/常规卡片间距
    T_SPACING_COMMON_XXLG: '24px',
    //
    T_SPACING_COMMON_XXXLG: '32px',
    // 大正方形的宽度/高度
    T_SQUARE_LG: '32px',
    // 中正方形的宽度/高度
    T_SQUARE_MD: '28px',
    // 小正方形的宽度/高度
    T_SQUARE_SM: '24px',
    // 开关/圆点/背景色/禁用
    T_SWITCH_COLOR_BG_DOT_DISABLED: '#cccccc',
    // 开关/圆点/背景色/关
    T_SWITCH_COLOR_BG_DOT_OFF: '#f44336',
    // 开关/圆点/背景色/开
    T_SWITCH_COLOR_BG_DOT_ON: '#15AD31',
    // 开关/内圈/背景色/关
    T_SWITCH_COLOR_BG_INNER_OFF: '#f6f6fb',
    // 开关/内圈/背景色/开
    T_SWITCH_COLOR_BG_INNER_ON: '#15AD31',
    // 开关/外圈/背景色
    T_SWITCH_COLOR_BG_OUTER: '#ffffff',
    // 开关/内圈/边框/开
    T_SWITCH_COLOR_LINE_INNER_ON: '#E6FFED',
    // 开关/文本色/关
    T_SWITCH_COLOR_TEXT_OFF: '#526075',
    // 开关/文本色/开
    T_SWITCH_COLOR_TEXT_ON: '#ffffff',
    // 开关/圆角
    T_SWITCH_CORNER: '2px',
    // 表格/标题/背景色
    T_TABLE_HEADER_COLOR_BG_DEFAULT: '#ffffff',
    // 表格/行/背景色
    T_TABLE_ROW_COLOR_BG_DEFAULT: '#f6f6fb',
    // 表格/行/背景色/hover
    T_TABLE_ROW_COLOR_BG_HOVER: '#EAEEFD',
    // 导航切换选中项/背景色
    T_TABS_DEFAULT_COLOR_BG_DEFAULT: '#ebedf5',
    // 导航切换/背景色/hover
    T_TABS_DEFAULT_COLOR_BG_HOVER: '#fafafc',
    // 导航切换/边框色/hover
    T_TABS_DEFAULT_COLOR_LINE_HOVER: '#efeff8',
    // hover状态背景色
    T_TABS_PRODUCT_COLOR_BG_HOVER: 'rgba(233,237,245,0.5)',
    // 导航切换/边框色/active
    T_TABS_PRODUCT_COLOR_LINE_ACTIVE: '#dfe0f1',
    // 默认状态阴影色值
    T_TABS_PRODUCT_COLOR_SHADOW_DEFAULT: '#edf0fd',
    // hover状态阴影色值
    T_TABS_PRODUCT_COLOR_SHADOW_HOVER: '#dee1e9',
    // 默认状态文本色值
    T_TABS_PRODUCT_COLOR_TEXT_DEFAULT: 'rgba(0,0,0,0.7)',
    // 一般用于备注/正文，是浏览器识别的最小字号
    T_TYPO_FONT_SIZE_1: '12px',
    // 一般用于正文或者小标题
    T_TYPO_FONT_SIZE_2: '14px',
    // 一般用于标题
    T_TYPO_FONT_SIZE_3: '16px',
    // 一般用于数字
    T_TYPO_FONT_SIZE_4: '18px',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPO_FONT_SIZE_5: '20px',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPO_FONT_SIZE_6: '24px',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPO_FONT_SIZE_7: '28px',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPO_FONT_SIZE_8: '32px',
    // 粗体字
    T_TYPO_FONT_WEIGHT_BOLD: '600',
    // 细体字
    T_TYPO_FONT_WEIGHT_LIGHT: '300',
    // 默认字体粗细，常规
    T_TYPO_FONT_WEIGHT_NORMAL: '400',
    // 宽松的行高，字号1.7倍
    T_TYPO_LINE_HEIGHT_LG: '1.7',
    // 中等的行高，字号1.5倍
    T_TYPO_LINE_HEIGHT_MD: '1.5',
    // 密集的行高，字号1.3倍
    T_TYPO_LINE_HEIGHT_SM: '1.3',
    // 大号控件宽度
    T_WIDTH_LG: '320px',
    // 中号控件宽度
    T_WIDTH_MD: '192px',
    // 小号控件宽度
    T_WIDTH_SM: '144px'
};
