// Do not edit directly
// Generated with design-token-editor on 2024/12/10 20:00:05

export default {
    // 按钮加载遮罩
    T_BUTTON_COMMON_COLOR_MASK: '#141A2B',
    // 按钮/备用/背景色/默认
    T_BUTTON_OTHER_COLOR_BG_DEFAULT: '#0B1224',
    // 按钮/备用/背景色/hover
    T_BUTTON_OTHER_COLOR_BG_HOVER: '#141A2B',
    // 按钮/备用/边框/默认
    T_BUTTON_OTHER_COLOR_BORDER_DEFAULT: '#2B3555',
    // 按钮/备用/边框/hover
    T_BUTTON_OTHER_COLOR_BORDER_HOVER: '#738BFF',
    // 按钮/备用/投影/默认
    T_BUTTON_OTHER_COLOR_SHADOW_DEFAULT: '0 0 0 0 rgba(0,0,0,0.12),inset 0 0 0 0 #2b3555',
    // 按钮/备用/投影/hover
    T_BUTTON_OTHER_COLOR_SHADOW_HOVER: '0 0 0 0 rgba(0,0,0,0.12),inset 0 0 0 0 #2b3555',
    // 按钮/主/背景色
    T_BUTTON_PRIMARY_COLOR_BG_DEFAULT: 'linear-gradient(135deg, #6488fc 0%,#3860f4 100%)',
    // 按钮/主/背景色/hover
    T_BUTTON_PRIMARY_COLOR_BG_HOVER: 'linear-gradient(135deg, #5c76e8 0%,#3357df 100%)',
    // 按钮/投影/默认
    T_BUTTON_PRIMARY_COLOR_SHADOW_DEFAULT:
        '0 2px 4px -1px #3458DE, inset 0 -3px 0 0 rgba(0,0,0,0.12), inset 0 1px 0 0 rgba(0,0,0,0.12)',
    // 按钮/投影/hover
    T_BUTTON_PRIMARY_COLOR_SHADOW_HOVER:
        '0 5px 8px -4px #3458DE, inset 0 -3px 0 0 rgba(0,0,0,0.12), inset 0 1px 0 0 rgba(0,0,0,0.12)',
    // 按钮/主/文本色
    T_BUTTON_PRIMARY_COLOR_TEXT_DEFAULT: '#ffffff',
    // 按钮/次/背景色/默认
    T_BUTTON_SECONDARY_COLOR_BG_DEFAULT: '#242B40',
    // 按钮/次/背景色/hover
    T_BUTTON_SECONDARY_COLOR_BG_HOVER: '#141A2B',
    // 按钮/次/边框/默认
    T_BUTTON_SECONDARY_COLOR_BORDER_DEFAULT: '#3F4A70',
    // 按钮/次/边框/hover
    T_BUTTON_SECONDARY_COLOR_BORDER_HOVER: '#2B3555',
    // 按钮/次/投影/默认
    T_BUTTON_SECONDARY_COLOR_SHADOW_DEFAULT: '0 2px 3px 0 rgba(0,0,0,0.12),inset 0 -2px 0 0 #2b3555',
    // 按钮/次/投影/hover
    T_BUTTON_SECONDARY_COLOR_SHADOW_HOVER:
        '0 0 1px 0 rgba(0,0,0,0.12),0 8px 12px -4px rgba(0,0,0,0.12),0 2px 1px -1px rgba(0,0,0,0.05), inset 0 -2px 0 0 #2b3555',
    // 操作区/间距/下
    T_CARD_ACTION_BOTTOM: '0px',
    // 操作区/间距/左
    T_CARD_ACTION_LEFT: '24px',
    // 操作区/间距/右
    T_CARD_ACTION_RIGHT: '24px',
    // 操作区/间距/上
    T_CARD_ACTION_TOP: '16px',
    // 卡片/背景色
    T_CARD_COLOR_BG_DEFAULT: '#141A2B',
    // 卡片描述/字体颜色
    T_CARD_COMMENT_FONT_COLOR_DEFAULT: '#C5CAE3',
    // 卡片描述/字体粗细
    T_CARD_COMMENT_FONT_FONT_WEIGHT: '400',
    // 卡片描述/字体行高
    T_CARD_COMMENT_FONT_LINE_HEIGHT: '1.7',
    // 卡片描述/字体大小
    T_CARD_COMMENT_FONT_SIZE: '12px',
    // 内容区域/背景/Pro组件token
    T_CARD_CONTENT_BG_DEFAULT: '#0B1224',
    // 内容区域/间距/下
    T_CARD_CONTENT_PADDING_BOTTOM: '0px',
    // 内容区域/间距/左
    T_CARD_CONTENT_PADDING_LEFT: '24px',
    // 内容区域/间距/右
    T_CARD_CONTENT_PADDING_RIGHT: '24px',
    // 内容区域/间距/上
    T_CARD_CONTENT_PADDING_TOP: '16px',
    // 底部/外间距/下
    T_CARD_FOOTER_MARGIN_BOTTOM: '24px',
    // 底部/外间距/上
    T_CARD_FOOTER_MARGIN_TOP: '24px',
    // 底部/间距/下
    T_CARD_FOOTER_PADDING_BOTTOM: '16px',
    // 底部/间距/左
    T_CARD_FOOTER_PADDING_LEFT: '24px',
    // 底部/间距/右
    T_CARD_FOOTER_PADDING_RIGHT: '24px',
    // 底部/间距/上
    T_CARD_FOOTER_PADDING_TOP: '16px',
    // 标题/字体颜色
    T_CARD_HEADER_FONT_COLOR_DEFAULT: '#F7F9FF',
    // 标题/字体粗细
    T_CARD_HEADER_FONT_FONT_WEIGHT: '600',
    // 标题/字体行高
    T_CARD_HEADER_FONT_LINE_HEIGHT: '1.7',
    // 标题/字体大小
    T_CARD_HEADER_FONT_SIZE: '16px',
    // 标题区域/间距/下
    T_CARD_HEADER_PADDING_BOTTOM: '0px',
    // 标题区域/间距/左
    T_CARD_HEADER_PADDING_LEFT: '24px',
    // 标题区域/间距/右
    T_CARD_HEADER_PADDING_RIGHT: '24px',
    // 标题区域/间距/上
    T_CARD_HEADER_PADDING_TOP: '24px',
    // 分割线/线条/提示/浅色
    T_CARD_LINE_COLOR_DEFAULT: '#2B3555',
    // 分割线/subArea/间距/
    T_CARD_LINE_PADDING_VERTICAL: '16px',
    // 卡片/外边距
    T_CARD_OUTSIDE_PADDING: '24px',
    // 二级标题/字体颜色
    T_CARD_SECONDARY_FONT_COLOR_DEFAULT: '#F7F9FF',
    // 二级标题/字体粗细
    T_CARD_SECONDARY_FONT_FONT_WEIGHT: '600',
    // 二级标题/字体行高
    T_CARD_SECONDARY_FONT_LINE_HEIGHT: '1.7',
    // 二级标题/字体大小
    T_CARD_SECONDARY_FONT_SIZE: '14px',
    // 二级标题/间距/下
    T_CARD_SECONDARY_PADDING_BOTTOM: '16px',
    // 图表/时间范围选择器/背景色
    T_CHART_TIMEPICKER_BG_DEFAULT: '#2F3852',
    // 图表/时间范围选择器/icon
    T_CHART_TIMEPICKER_ICON_DEFAULT: '#304FC2',
    // 背景/渐变/内容区
    T_COLOR_BG_CONTENT_1: 'linear-gradient(180deg, #1a2132 0%, #1a2132 100%)',
    // 背景/常规/亮色
    T_COLOR_BG_DEFAULT_BRIGHT: '#141A2B',
    // 背景/常规/深色
    T_COLOR_BG_DEFAULT_DARK: '#161C2E',
    // 背景/常规/hover
    T_COLOR_BG_DEFAULT_HOVER: '#2b3555',
    // 背景/常规/浅色
    T_COLOR_BG_DEFAULT_LIGHT: '#0B1224',
    // 背景/常规/默认色，替换为T_COLOR_BG_DEFAULT_BRIGHT
    T_COLOR_BG_DEFAULT_NORMAL: '#141A2B',
    // 背景/禁用状态/深色
    T_COLOR_BG_DISABLED_DARK: '#535763',
    // 背景/禁用状态/浅色
    T_COLOR_BG_DISABLED_LIGHT: '#1A202F',
    // 背景/错误状态/深色
    T_COLOR_BG_ERROR_DARK: '#db3f3f',
    // 背景/错误状态/浅色
    T_COLOR_BG_ERROR_LIGHT: '#2e1b1e',
    // 背景/高亮
    T_COLOR_BG_HIGHLIGHT: '#f8e382',
    // 背景/菜单
    T_COLOR_BG_MENU: '#242B40',
    // 背景/提示状态/深色
    T_COLOR_BG_NOTICE_DARK: '#526075',
    // 背景/提示状态/浅色
    T_COLOR_BG_NOTICE_LIGHT: '#1C233D',
    // 背景/纯色/品牌色1
    T_COLOR_BG_PRIMARY_1: '#5A76FF',
    // 背景/纯色/品牌色2
    T_COLOR_BG_PRIMARY_2: '#738BFF',
    // 背景/渐变/品牌色3
    T_COLOR_BG_PRIMARY_3: 'linear-gradient(135deg, #6488fc 0%,#3860f4 100%)',
    // 背景/渐变/品牌色4
    T_COLOR_BG_PRIMARY_4: 'linear-gradient(135deg, #5c76e8 0%,#3357df 100%)',
    // 背景/浅色/品牌色5
    T_COLOR_BG_PRIMARY_5: '#1B2341',
    // 背景/侧边栏
    T_COLOR_BG_SIDEBAR: '#e7e9f3',
    // 背景/成功状态/深色
    T_COLOR_BG_SUCCESS_DARK: '#2b9f56',
    // 背景/成功状态/浅色
    T_COLOR_BG_SUCCESS_LIGHT: '#1e3019',
    // 背景/透明
    T_COLOR_BG_TRANSPARENT: 'rgba(0,0,0,0)',
    // 背景/警告状态/深色
    T_COLOR_BG_WARNING_DARK: '#ebb73d',
    // 背景/警告状态/浅色
    T_COLOR_BG_WARNING_LIGHT: '#2e281b',
    // 背景/白色，替换为T_COLOR_BG_DEFAULT_BRIGHT
    T_COLOR_BG_WHITE: '#141A2B',
    // 图例/蓝-1
    T_COLOR_LEGEND_BLUE_1: '#15253b',
    // 图例/蓝-2
    T_COLOR_LEGEND_BLUE_2: '#29476d',
    // 图例/蓝-3
    T_COLOR_LEGEND_BLUE_3: '#335d8f',
    // 图例/蓝-4
    T_COLOR_LEGEND_BLUE_4: '#4478b5',
    // 图例/蓝-5
    T_COLOR_LEGEND_BLUE_5: '#70a6ec',
    // 图例/蓝-6
    T_COLOR_LEGEND_BLUE_6: '#90bcf6',
    // 图例/蓝-7
    T_COLOR_LEGEND_BLUE_7: '#a1c3ef',
    // 图例/蓝-8
    T_COLOR_LEGEND_BLUE_8: '#b7d1f4',
    // 图例/蓝-9
    T_COLOR_LEGEND_BLUE_9: '#d8e9ff',
    // 图例/青-1
    T_COLOR_LEGEND_CYAN_1: '#1d2c29',
    // 图例/青-2
    T_COLOR_LEGEND_CYAN_2: '#1e3c37',
    // 图例/青-3
    T_COLOR_LEGEND_CYAN_3: '#1f4b45',
    // 图例/青-4
    T_COLOR_LEGEND_CYAN_4: '#2f7a6d',
    // 图例/青-5
    T_COLOR_LEGEND_CYAN_5: '#3eaa95',
    // 图例/青-6
    T_COLOR_LEGEND_CYAN_6: '#4ed9bd',
    // 图例/青-7
    T_COLOR_LEGEND_CYAN_7: '#6de3d1',
    // 图例/青-8
    T_COLOR_LEGEND_CYAN_8: '#8eece5',
    // 图例/青-9
    T_COLOR_LEGEND_CYAN_9: '#adf3f6',
    // 图例/绿-1
    T_COLOR_LEGEND_GREEN_1: '#1e3019',
    // 图例/绿-2
    T_COLOR_LEGEND_GREEN_2: '#214819',
    // 图例/绿-3
    T_COLOR_LEGEND_GREEN_3: '#236019',
    // 图例/绿-4
    T_COLOR_LEGEND_GREEN_4: '#26752d',
    // 图例/绿-5
    T_COLOR_LEGEND_GREEN_5: '#288a42',
    // 图例/绿-6
    T_COLOR_LEGEND_GREEN_6: '#2b9f56',
    // 图例/绿-7
    T_COLOR_LEGEND_GREEN_7: '#60bd7c',
    // 图例/绿-8
    T_COLOR_LEGEND_GREEN_8: '#95dca2',
    // 图例/绿-9
    T_COLOR_LEGEND_GREEN_9: '#cafac8',
    // 图例/浅蓝-1
    T_COLOR_LEGEND_LIGHTBLUE_1: '#1c252d',
    // 图例/浅蓝-2
    T_COLOR_LEGEND_LIGHTBLUE_2: '#1a2f37',
    // 图例/浅蓝-3
    T_COLOR_LEGEND_LIGHTBLUE_3: '#1d434e',
    // 图例/浅蓝-4
    T_COLOR_LEGEND_LIGHTBLUE_4: '#2b6e7e',
    // 图例/浅蓝-5
    T_COLOR_LEGEND_LIGHTBLUE_5: '#399bb0',
    // 图例/浅蓝-6
    T_COLOR_LEGEND_LIGHTBLUE_6: '#47c7e1',
    // 图例/浅蓝-7
    T_COLOR_LEGEND_LIGHTBLUE_7: '#67cde9',
    // 图例/浅蓝-8
    T_COLOR_LEGEND_LIGHTBLUE_8: '#89d3f1',
    // 图例/浅蓝-9
    T_COLOR_LEGEND_LIGHTBLUE_9: '#a9d9f9',
    // 图例/橙-1
    T_COLOR_LEGEND_ORANGE_1: '#2e231b',
    // 图例/橙-2
    T_COLOR_LEGEND_ORANGE_2: '#402c1a',
    // 图例/橙-3
    T_COLOR_LEGEND_ORANGE_3: '#51351a',
    // 图例/橙-4
    T_COLOR_LEGEND_ORANGE_4: '#845126',
    // 图例/橙-5
    T_COLOR_LEGEND_ORANGE_5: '#b86d31',
    // 图例/橙-6
    T_COLOR_LEGEND_ORANGE_6: '#eb883d',
    // 图例/橙-7
    T_COLOR_LEGEND_ORANGE_7: '#f2a65f',
    // 图例/橙-8
    T_COLOR_LEGEND_ORANGE_8: '#f8c382',
    // 图例/橙-9
    T_COLOR_LEGEND_ORANGE_9: '#ffe0a4',
    // 图例/紫-1
    T_COLOR_LEGEND_PURPLE_1: '#2b1d39',
    // 图例/紫-2
    T_COLOR_LEGEND_PURPLE_2: '#4d3465',
    // 图例/紫-3
    T_COLOR_LEGEND_PURPLE_3: '#674886',
    // 图例/紫-4
    T_COLOR_LEGEND_PURPLE_4: '#8863ae',
    // 图例/紫-5
    T_COLOR_LEGEND_PURPLE_5: '#b186dc',
    // 图例/紫-6
    T_COLOR_LEGEND_PURPLE_6: '#c499ef',
    // 图例/紫-7
    T_COLOR_LEGEND_PURPLE_7: '#d5b1f9',
    // 图例/紫-8
    T_COLOR_LEGEND_PURPLE_8: '#e0c6fa',
    // 图例/紫-9
    T_COLOR_LEGEND_PURPLE_9: '#eddbff',
    // 图例/红-1
    T_COLOR_LEGEND_RED_1: '#2e1b1e',
    // 图例/红-2
    T_COLOR_LEGEND_RED_2: '#4c2525',
    // 图例/红-3
    T_COLOR_LEGEND_RED_3: '#6a2e2b',
    // 图例/红-4
    T_COLOR_LEGEND_RED_4: '#903432',
    // 图例/红-5
    T_COLOR_LEGEND_RED_5: '#b53938',
    // 图例/红-6
    T_COLOR_LEGEND_RED_6: '#db3f3f',
    // 图例/红-7
    T_COLOR_LEGEND_RED_7: '#e75f5f',
    // 图例/红-8
    T_COLOR_LEGEND_RED_8: '#f37f7f',
    // 图例/红-9
    T_COLOR_LEGEND_RED_9: '#ff9f9f',
    // 图例/黄-1
    T_COLOR_LEGEND_YELLOW_1: '#2e281b',
    // 图例/黄-2
    T_COLOR_LEGEND_YELLOW_2: '#40361a',
    // 图例/黄-3
    T_COLOR_LEGEND_YELLOW_3: '#51441a',
    // 图例/黄-4
    T_COLOR_LEGEND_YELLOW_4: '#846a26',
    // 图例/黄-5
    T_COLOR_LEGEND_YELLOW_5: '#b89131',
    // 图例/黄-6
    T_COLOR_LEGEND_YELLOW_6: '#ebb73d',
    // 图例/黄-7
    T_COLOR_LEGEND_YELLOW_7: '#f2cd5f',
    // 图例/黄-8
    T_COLOR_LEGEND_YELLOW_8: '#f8e382',
    // 图例/黄-9
    T_COLOR_LEGEND_YELLOW_9: '#fff9a4',
    // 线条/常规/深色
    T_COLOR_LINE_DEFAULT_DARK: '#3F4A70',
    // 线条/常规/浅色
    T_COLOR_LINE_DEFAULT_LIGHT: '#2B3555',
    // 线条/常规/透明
    T_COLOR_LINE_DEFAULT_TRANSPARENT: 'rgba(0,0,0,0)',
    // 线条/禁用/深色
    T_COLOR_LINE_DISABLED_DARK: '#535763',
    // 线条/禁用/浅色
    T_COLOR_LINE_DISABLED_LIGHT: '#2B313F',
    // 线条/错误/深色
    T_COLOR_LINE_ERROR_DARK: '#db3f3f',
    // 线条/错误/浅色
    T_COLOR_LINE_ERROR_LIGHT: '#6a2e2b',
    // 线条/提示/深色
    T_COLOR_LINE_NOTICE_DARK: '#526075',
    // 线条/提示/浅色
    T_COLOR_LINE_NOTICE_LIGHT: '#2C3D72',
    // 线条/主色
    T_COLOR_LINE_PRIMARY_DEFAULT: '#5A76FF',
    // 线条/主色/hover
    T_COLOR_LINE_PRIMARY_HOVER: '#738BFF',
    // 线条/浅色
    T_COLOR_LINE_PRIMARY_LIGHT: '#2b3555',
    // 线条/正确/深色
    T_COLOR_LINE_SUCCESS_DARK: '#2b9f56',
    // 线条/正确/浅色
    T_COLOR_LINE_SUCCESS_LIGHT: '#236019',
    // 线条/警告/深色
    T_COLOR_LINE_WARNING_DARK: '#ebb73d',
    // 线条/警告/浅色
    T_COLOR_LINE_WARNING_LIGHT: '#51441a',
    // 蒙层/背景/抽屉/弹窗
    T_COLOR_MASK_BG: 'rgba(0,0,0,0.5)',
    // 蒙层/组件
    T_COLOR_MASK_COMP: 'rgba(20,26,43,0.5)',
    // 蒙层/全局
    T_COLOR_MASK_OVERALL: 'rgba(20,26,43,0.7)',
    // 文本/常规/亮色
    T_COLOR_TEXT_DEFAULT_BRIGHT: '#141A2B',
    // 文本/常规/深色
    T_COLOR_TEXT_DEFAULT_DARK: '#F7F9FF',
    // 文本/常规/浅色
    T_COLOR_TEXT_DEFAULT_LIGHT: '#C5CAE3',
    // 文本/常规/默认色，替换为T_COLOR_TEXT_DEFAULT_BRIGHT
    T_COLOR_TEXT_DEFAULT_NORMAL: '#141A2B',
    // 文本/禁用
    T_COLOR_TEXT_DISABLED: '#535763',
    // 文本/错误
    T_COLOR_TEXT_ERROR: '#db3f3f',
    // 文本/错误/深色
    T_COLOR_TEXT_ERROR_DARK: '#ff9f9f',
    // 文本/主色
    T_COLOR_TEXT_PRIMARY_DEFAULT: '#5A76FF',
    // 文本/主色/hover
    T_COLOR_TEXT_PRIMARY_HOVER: '#738BFF',
    // 文本/备注/深色
    T_COLOR_TEXT_REMARK_DARK: '#5C6586',
    // 文本/备注/浅色
    T_COLOR_TEXT_REMARK_LIGHT: 'rgba(247,249,255,0.2)',
    // 文本/正确
    T_COLOR_TEXT_SUCCESS: '#2b9f56',
    // 文本/正确/深色
    T_COLOR_TEXT_SUCCESS_DARK: '#cafac8',
    // 系统黑色文本
    T_COLOR_TEXT_SYSTEM_BLACK: '#000000',
    // 系统白色文本
    T_COLOR_TEXT_SYSTEM_WHITE: '#ffffff',
    // 文本/警告
    T_COLOR_TEXT_WARNING: '#ebb73d',
    // 文本/警告/深色
    T_COLOR_TEXT_WARNING_DARK: '#fff9a4',
    // 文本/白色，替换为T_COLOR_TEXT_DEFAULT_BRIGHT
    T_COLOR_TEXT_WHITE: '#141A2B',
    // 大号控件字号
    T_CONTROL_FONT_SIZE_LG: '12px',
    // 中号控件字号
    T_CONTROL_FONT_SIZE_MD: '12px',
    // 小号控件字号
    T_CONTROL_FONT_SIZE_SM: '12px',
    // 大号控件高度
    T_CONTROL_HEIGHT_LG: '32px',
    // 中号控件高度
    T_CONTROL_HEIGHT_MD: '28px',
    // 小号控件高度
    T_CONTROL_HEIGHT_SM: '24px',
    // 大号控件间距
    T_CONTROL_SPACING_LG: '8px',
    // 中号控件间距
    T_CONTROL_SPACING_MD: '8px',
    // 小号控件间距
    T_CONTROL_SPACING_SM: '8px',
    // 圆形
    T_CORNER_CIRCLE: '50%',
    // 大圆角，用于卡片圆角
    T_CORNER_LG: '4px',
    // 默认圆角，常用于按钮/输入框等
    T_CORNER_SM: '2px',
    // 直角
    T_CORNER_ZERO: '0',
    // 抽屉/关闭操作/背景/默认/颜色
    T_DRAWER_CLOSE_BG_COLOR_DEFAULT: 'rgba(0,0,0,0.3)',
    // 抽屉/关闭操作/背景/悬停/颜色
    T_DRAWER_CLOSE_BG_COLOR_HOVER: 'rgba(0,0,0,0.5)',
    // 抽屉/关闭操作/背景/默认/尺寸
    T_DRAWER_CLOSE_BG_SIZE_DEFAULT: '32px',
    // 抽屉/关闭操作/背景/悬停/尺寸
    T_DRAWER_CLOSE_BG_SIZE_HOVER: '32px',
    // 抽屉/关闭操作/icon/默认/颜色
    T_DRAWER_CLOSE_ICON_COLOR_DEFAULT: '#141A2B',
    // 抽屉/关闭操作/icon/悬停/颜色
    T_DRAWER_CLOSE_ICON_COLOR_HOVER: '#141A2B',
    // 抽屉/关闭操作/icon/默认/尺寸
    T_DRAWER_CLOSE_ICON_SIZE_DEFAULT: '14px',
    // 抽屉/关闭操作/icon/悬停/尺寸
    T_DRAWER_CLOSE_ICON_SIZE_HOVER: '14px',
    // 抽屉/内容/背景/颜色
    T_DRAWER_CONTENT_BG_COLOR: 'linear-gradient(180deg, #1a2132 0%, #1a2132 100%)',
    // 抽屉/内容/背景/内间距
    T_DRAWER_CONTENT_PADDING: '24px',
    // 抽屉/页头/标题背景/默认/颜色
    T_DRAWER_HEADER_BG_COLOR_DEFAULT: '#141A2B',
    // 抽屉/页头/标题背景/默认/阴影
    T_DRAWER_HEADER_BG_SHADOW_DEFAULT: '0 1px 0 0 #2B3555',
    // 抽屉/页头/背景/内间距（横向）
    T_DRAWER_HEADER_PADDING_HORIZONAL: '24px',
    // 抽屉/页头/背景/内间距（纵向）
    T_DRAWER_HEADER_PADDING_VERTICAL: '16px',
    // 抽屉/页头/标题/默认/尺寸
    T_DRAWER_HEADER_SIZE_DEFAULT: '14px',
    // 抽屉/页头/标题/默认/颜色
    T_DRAWER_HEADER_TITLE_COLOR_DEFAULT: '#F7F9FF',
    // 抽屉/蒙层/颜色
    T_DRAWER_MASK_COLOR: 'rgba(0,0,0,0.5)',
    // 抽屉/操作/背景/默认
    T_DRAWER_RESIZER_BG_DEFAULT: 'rgba(0,0,0,0.5)',
    // 抽屉/操作/背景/悬停
    T_DRAWER_RESIZER_BG_HOVER: 'rgba(0,0,0,0.5)',
    // 抽屉/下边/阴影
    T_DRAWER_SHADOW_BOTTOM:
        '0 46px 24px -35px rgba(0,0,0,0.05),0 25px 10px -16px rgba(0,0,0,0.05),0 10px 6px -6px rgba(0,0,0,0.05)',
    // 抽屉/左边/阴影
    T_DRAWER_SHADOW_LEFT:
        '-46px 0 24px -35px rgba(0,0,0,0.05),-25px 0 10px -16px rgba(0,0,0,0.05),-10px 0 6px -6px rgba(0,0,0,0.05)',
    // 抽屉/右边/阴影
    T_DRAWER_SHADOW_RIGHT:
        '46px 0 24px -35px rgba(0,0,0,0.05),25px 0 10px -16px rgba(0,0,0,0.05),10px 0 6px -6px rgba(0,0,0,0.05)',
    // 抽屉/上边/阴影
    T_DRAWER_SHADOW_TOP:
        '0 -46px 24px -35px rgba(0,0,0,0.05),0 -25px 10px -16px rgba(0,0,0,0.05),0 -10px 6px -6px rgba(0,0,0,0.05)',
    // 表单项/垂直间距
    T_FORM_ITEM_SPACING_VERTICAL: '16px',
    // 顶部导航左侧LOGO背景色
    T_FRAME_LOGO_COLOR_BG_DEFAULT: '#5A76FF',
    // 全部产品列表/图标颜色
    T_FRAME_PRODUCTS_COLOR_TEXT_ICON: '#d8e9ff',
    // 全局左侧收藏栏选中的产品背景色
    T_FRAME_SIDEBAR_COLOR_BG_ACTIVE: '#1B2341',
    // 全局左侧收藏栏默认背景色
    T_FRAME_SIDEBAR_COLOR_BG_DEFAULT: '#141A2B',
    // 全局左侧收藏栏展开状态背景色
    T_FRAME_SIDEBAR_COLOR_BG_EXPAND: '#141A2B',
    // 顶部导航默认背景色
    T_FRAME_TOP_COLOR_BG_DEFAULT: 'linear-gradient(180deg, #1a2132 0%, #1a2132 100%)',
    // 顶部导航hover背景色/Logo背景色
    T_FRAME_TOP_COLOR_BG_HOVER: '#141A2B',
    // 大号控件高度
    T_HEIGHT_LG: '32px',
    // 中号控件高度
    T_HEIGHT_MD: '28px',
    // 小号控件高度
    T_HEIGHT_SM: '24px',
    // 代码编辑器/读写/背景色/操作
    T_IDE_DEFAULT_COLOR_BG_ACTION: 'rgba(0,0,0,0.32)',
    // 代码编辑器/读写/背景色/默认
    T_IDE_DEFAULT_COLOR_BG_DEFAULT: '#F7F9FF',
    // 代码编辑器/只读/背景色/操作
    T_IDE_READONLY_COLOR_BG_ACTION: 'rgba(247,249,255,0.12)',
    // 代码编辑器/只读/背景色/默认
    T_IDE_READONLY_COLOR_BG_DEFAULT: '#161C2E',
    // 输入框/背景色/激活
    T_INPUT_COLOR_BG_ACTIVE: '#161C2E',
    // 输入框/背景色/默认
    T_INPUT_COLOR_BG_DEFAULT: '#0B1224',
    // 输入框/背景色/高亮/默认
    T_INPUT_COLOR_BG_HL_DEFAULT: '#2b3555',
    // 输入框/背景色/高亮/错误
    T_INPUT_COLOR_BG_HL_ERROR: '#6a2e2b',
    // 输入框/阴影/默认
    T_INPUT_COLOR_SHADOW_DEFAULT: 'inset 0 3px 0 0 rgba(0,0,0,0.05)',
    // 输入框/阴影/错误
    T_INPUT_COLOR_SHADOW_ERROR: 'inset 0 1px 3px 0 #6a2e2b',
    // 默认线条，实线
    T_LINE_STYLE_BASE: 'solid',
    // 虚线边框样式，用于添加/上传照片按钮
    T_LINE_STYLE_DASHED: 'dashed',
    // 默认线条高
    T_LINE_WIDTH_BASE: '1px',
    // 粗线条
    T_LINE_WIDTH_LG: '2px',
    // 无线条
    T_LINE_WIDTH_SM: '0px',
    // 列内容文本颜色/文本/常规/深色
    T_LIST_CONTENT_FONT_COLOR_DEFAULT: '#F7F9FF',
    // 列内容文本颜色/文本/备注/深色
    T_LIST_CONTENT_FONT_COLOR_REMARK: '#5C6586',
    // 列内容文本加粗状态/默认字体粗细，常规
    T_LIST_CONTENT_FONT_FONT_WEIGHT: '400',
    // 列内容行高/宽松的行高，字号1.7倍
    T_LIST_CONTENT_FONT_LINE_HEIGHT: '1.7',
    // 列内容文本/一般用于备注/正文，是浏览器识别的最小字号
    T_LIST_CONTENT_FONT_SIZE: '12px',
    // 列标题文本颜色/文本/常规/浅色
    T_LIST_HEADER_FONT_COLOR_DEFAULT: '#C5CAE3',
    // 列标题文本加粗状态/默认字体粗细，常规
    T_LIST_HEADER_FONT_FONT_WEIGHT: '400',
    // 列标题行高/宽松的行高，字号1.7倍
    T_LIST_HEADER_FONT_LINE_HEIGHT: '1.7',
    // 列标题文本/一般用于备注/正文，是浏览器识别的最小字号
    T_LIST_HEADER_FONT_SIZE: '12px',
    // 排版link中icon的默认颜色
    T_LIST_ICON_LINK_DEFAULT: '#3F4A70',
    // 排版link中icon的hover颜色
    T_LIST_ICON_LINK_HOVER: '#738BFF',
    // 列项内间距/左右间距
    T_LIST_ITEM_PADDING_HORIZONAL: '0',
    // 列项内间距/上下间距
    T_LIST_ITEM_PADDING_VERTICAL: '8px',
    // 列分割线/线条/提示/浅色
    T_LIST_LINE_COLOR_DEFAULT: '#2B3555',
    // 列项布局间距/左右间距
    T_LIST_OUTSIDE_PADDING_HORIZONAL: '20px',
    // 列项布局间距/上下间距
    T_LIST_OUTSIDE_PADDING_VERTICAL: '0',
    // 加载底部蒙层
    T_LOADING_COLOR_LAYER_DEFAULT: 'rgba(20,26,43,0.7)',
    // 弹窗/抽屉/通用/蒙层
    T_MODAL_COLOR_LAYER_DEFAULT: 'rgba(0,0,0,0.5)',
    // 弹窗/阴影
    T_MODAL_SHADOW_DEFAULT:
        '0 3px 6px -4px rgba(0,0,0,0.32),0 6px 16px 0 rgba(0,0,0,0.28),0 9px 28px 8px rgba(0,0,0,0.25)',
    // 左侧订单模块背景
    T_PAY_COLOR_BG_1: 'linear-gradient(180deg, #1a2132 0%, #1a2132 100%)',
    // 右侧计费模块背景
    T_PAY_COLOR_BG_2: '#161C2E',
    // 左侧订单卡片下半段背景
    T_PAY_COLOR_BG_3: '#1F2538',
    // 弹出层/背景色/暗
    T_POPOVER_COLOR_BG_DARK: '#C5CAE3',
    // 弹出层/背景色/亮
    T_POPOVER_COLOR_BG_LIGHT: '#3F4A70',
    // 弹出层/边框/暗
    T_POPOVER_COLOR_LINE_DARK: 'rgba(0,0,0,0)',
    // 弹出层/边框/亮
    T_POPOVER_COLOR_LINE_LIGHT: 'rgba(0,0,0,0)',
    // 进度条/背景色
    T_PROGRESS_COLOR_BG_DEFAULT: '#192036',
    // 单选框/卡片标题/背景色/激活
    T_RADIO_CARD_COLOR_BG_ACTIVE: '#0B1224',
    // 单选框/卡片标题/背景色/激活
    T_RADIO_HEADER_COLOR_BG_ACTIVE: '#0B1224',
    // 滚动条/背景色
    T_SCROLLBAR_COLOR_BG_DEFAULT: 'rgba(255,255,255,0.25)',
    // 滚动条/边框色
    T_SCROLLBAR_COLOR_BORDER_DEFAULT: 'rgba(0,0,0,0.5)',
    // 块/下/大
    T_SHADOW_BLOCK_BOTTOM_LG:
        '0 46px 24px -35px rgba(0,0,0,0.25),0 25px 10px -16px rgba(0,0,0,0.25),0 10px 6px -6px rgba(0,0,0,0.25)',
    // 块/下/小
    T_SHADOW_BLOCK_BOTTOM_SM: '0 3px 3px -2px rgba(0,0,0,0.25),0 8px 6px -6px rgba(0,0,0,0.28)',
    // 块/常规/大
    T_SHADOW_BLOCK_DEFAULT_LG:
        '0 6px 16px 0 rgba(0,0,0,0.25), 0 16px 24px -8px rgba(0,0,0,0.28), 0 0 16px 0 rgba(0,0,0,0.25),inset 0 -2px 0px 0px rgba(0,0,0,0.28)',
    // 块/常规/中
    T_SHADOW_BLOCK_DEFAULT_MD:
        '0 0 1px 0 rgba(0,0,0,0.32), 0 8px 12px -4px rgba(0,0,0,0.32), 0 4px 4px -2px rgba(0,0,0,0.25),inset 0 -2px 0px 0px rgba(0,0,0,0.28)',
    // 块/常规/小
    T_SHADOW_BLOCK_DEFAULT_SM:
        '0 0 2px 0 rgba(0,0,0,0.28), 0 5px 8px -4px rgba(0,0,0,0.32), 0 1px 0 0 rgba(0,0,0,0.25),inset 0 -1px 0px 0px rgba(0,0,0,0.28)',
    // 块/左/大
    T_SHADOW_BLOCK_LEFT_LG:
        '-46px 0 24px -35px rgba(0,0,0,0.25),-25px 0 10px -16px rgba(0,0,0,0.25),-10px 0 6px -6px rgba(0,0,0,0.25)',
    // 块/左/小
    T_SHADOW_BLOCK_LEFT_SM: '-3px 0 3px -2px rgba(0,0,0,0.25),-8px 0 6px -6px rgba(0,0,0,0.28)',
    // 块/右/大
    T_SHADOW_BLOCK_RIGHT_LG:
        '46px 0 24px -35px rgba(0,0,0,0.25),25px 0 10px -16px rgba(0,0,0,0.25),10px 0 6px -6px rgba(0,0,0,0.25)',
    // 块/右/小
    T_SHADOW_BLOCK_RIGHT_SM: '3px 0 3px -2px rgba(0,0,0,0.25),8px 0 6px -6px rgba(0,0,0,0.28)',
    // 块/上/大
    T_SHADOW_BLOCK_TOP_LG:
        '0 -46px 24px -35px rgba(0,0,0,0.25),0 -25px 10px -16px rgba(0,0,0,0.25),0 -10px 6px -6px rgba(0,0,0,0.25)',
    // 块/上/小
    T_SHADOW_BLOCK_TOP_SM: '0 -3px 3px -2px rgba(0,0,0,0.25),0 -8px 6px -6px rgba(0,0,0,0.28)',
    // 按钮/白/默认
    T_SHADOW_BUTTON_DEFAULT: '0 2px 3px 0 rgba(0,0,0,0.32),inset 0 -2px 0 0 #2b3555',
    // 按钮/错误色/默认
    T_SHADOW_BUTTON_ERROR: '0 1px 3px -1px #db3f3f',
    // 按钮/错误色/hover
    T_SHADOW_BUTTON_ERROR_HOVER: '0 5px 8px -4px #db3f3f',
    // 按钮/白/hover
    T_SHADOW_BUTTON_HOVER:
        '0 0 1px 0 rgba(0,0,0,0.32),0 8px 12px -4px rgba(0,0,0,0.32),0 2px 1px -1px rgba(0,0,0,0.25), inset 0 -2px 0 0 #2b3555',
    // 按钮/品牌色/默认
    T_SHADOW_BUTTON_PRIMARY:
        '0 2px 4px -1px #3458DE, inset 0 -3px 0 0 rgba(0,0,0,0.32), inset 0 1px 0 0 rgba(0,0,0,0.32)',
    // 按钮/品牌色/hover
    T_SHADOW_BUTTON_PRIMARY_HOVER:
        '0 5px 8px -4px #3458DE, inset 0 -3px 0 0 rgba(0,0,0,0.32), inset 0 1px 0 0 rgba(0,0,0,0.32)',
    // 内阴影/输入框
    T_SHADOW_INSET_1: 'inset 0 1px 3px 0 #2B3555',
    // 内阴影/下
    T_SHADOW_INSET_BOTTOM: 'inset 0 -10px 8px -8px rgba(0,0,0,0.32)',
    // 内阴影/默认
    T_SHADOW_INSET_DEFAULT: 'inset 0 3px 0 0 rgba(0,0,0,0.25)',
    // 内阴影/错误
    T_SHADOW_INSET_ERROR: 'inset 0 1px 3px 0 #6a2e2b',
    // 内阴影/左
    T_SHADOW_INSET_LEFT: 'inset 10px 0 8px -8px rgba(0,0,0,0.32)',
    // 内阴影/右
    T_SHADOW_INSET_RIGHT: 'inset -10px 0 8px -8px rgba(0,0,0,0.32)',
    // 内阴影/上
    T_SHADOW_INSET_TOP: 'inset 0 10px 8px -8px rgba(0,0,0,0.32)',
    // 抽屉/页头/背景/线条
    T_SHADOW_LINE_BOTTOM: '0 1px 0 0 #2B3555',
    // 抽屉/页头/背景/线条
    T_SHADOW_LINE_LEFT: '-1px 0 0 0 #2B3555',
    // 抽屉/页头/背景/线条
    T_SHADOW_LINE_RIGHT: '1px 0 0 0 #2B3555',
    // 抽屉/页头/背景/线条
    T_SHADOW_LINE_TOP: '0 1px 0 0 #2B3555',
    // 骨架屏/背景色/深色
    T_SKELETON_COLOR_BG_DARK: '#1F2538',
    // 骨架屏/背景色/深色
    T_SKELETON_COLOR_BG_DARK1: 'rgba(0,0,0,0.5)',
    // 骨架屏/背景色/浅色
    T_SKELETON_COLOR_BG_LIGHT: '#161C2E',
    // 骨架屏/背景色/浅色
    T_SKELETON_COLOR_BG_LIGHT1: 'rgba(0,0,0,0.3)',
    // 滑块/背景色/激活
    T_SLIDER_COLOR_BG_ACTIVE: '#1B2341',
    // 滑块/背景色/未激活
    T_SLIDER_COLOR_BG_DEFAULT: '#0B1224',
    // 滑块/边框色/激活
    T_SLIDER_COLOR_LINE_ACTIVE: '#738BFF',
    // 滑块/边框色/未激活
    T_SLIDER_COLOR_LINE_DEFAULT: '#3F4A70',
    // 滑块/文本色/激活
    T_SLIDER_COLOR_TEXT_ACTIVE: '#738BFF',
    // 滑块/文本色/未激活
    T_SLIDER_COLOR_TEXT_DEFAULT: '#5C6586',
    // 弹窗内表单间纵向间距
    T_SPACING_COMMON_LG: '16px',
    // 大号按钮左右内间距/页面内按钮与按钮横向间距
    T_SPACING_COMMON_MD: '12px',
    // 中号按钮左右内间距/弹窗内按钮与按钮的横向间距
    T_SPACING_COMMON_SM: '8px',
    //
    T_SPACING_COMMON_XLG: '20px',
    // icon和文本之间的间距
    T_SPACING_COMMON_XS: '4px',
    // 页面内表单间纵向间距/常规卡片间距
    T_SPACING_COMMON_XXLG: '24px',
    //
    T_SPACING_COMMON_XXXLG: '32px',
    // 大正方形的宽度/高度
    T_SQUARE_LG: '32px',
    // 中正方形的宽度/高度
    T_SQUARE_MD: '28px',
    // 小正方形的宽度/高度
    T_SQUARE_SM: '24px',
    // 开关/圆点/背景色/禁用
    T_SWITCH_COLOR_BG_DOT_DISABLED: '#535763',
    // 开关/圆点/背景色/关
    T_SWITCH_COLOR_BG_DOT_OFF: '#db3f3f',
    // 开关/圆点/背景色/开
    T_SWITCH_COLOR_BG_DOT_ON: '#2b9f56',
    // 开关/内圈/背景色/关
    T_SWITCH_COLOR_BG_INNER_OFF: '#2B3555',
    // 开关/内圈/背景色/开
    T_SWITCH_COLOR_BG_INNER_ON: '#2b9f56',
    // 开关/外圈/背景色
    T_SWITCH_COLOR_BG_OUTER: '#0B1224',
    // 开关/内圈/边框/开
    T_SWITCH_COLOR_LINE_INNER_ON: '#1e3019',
    // 开关/文本色/关
    T_SWITCH_COLOR_TEXT_OFF: '#F7F9FF',
    // 开关/文本色/开
    T_SWITCH_COLOR_TEXT_ON: '#ffffff',
    // 开关/圆角
    T_SWITCH_CORNER: '2px',
    // 表格/标题/二级背景色
    T_TABLE_HEADER_COLOR_BG2: '#141A2B',
    // 表格/标题/背景色
    T_TABLE_HEADER_COLOR_BG_DEFAULT: '#141A2B',
    // 表格/标题/icon/颜色
    T_TABLE_HEADER_COLOR_ICON: '#F7F9FF',
    // 表格/行/背景色
    T_TABLE_ROW_COLOR_BG_DEFAULT: '#1F2538',
    // 表格/行/背景色/hover
    T_TABLE_ROW_COLOR_BG_HOVER: '#2b3555',
    // 导航切换选中项/背景色
    T_TABS_DEFAULT_COLOR_BG_DEFAULT: '#1a2132',
    // 导航切换/背景色/hover
    T_TABS_DEFAULT_COLOR_BG_HOVER: '#192036',
    // 导航切换/边框色/hover
    T_TABS_DEFAULT_COLOR_LINE_HOVER: '#192036',
    // hover状态背景色
    T_TABS_PRODUCT_COLOR_BG_HOVER: '#2F3852',
    // 导航切换/边框色/active
    T_TABS_PRODUCT_COLOR_LINE_ACTIVE: '#192036',
    // 默认状态阴影色值
    T_TABS_PRODUCT_COLOR_SHADOW_DEFAULT: '#262e47',
    // hover状态阴影色值
    T_TABS_PRODUCT_COLOR_SHADOW_HOVER: '#0c142a',
    // 默认状态文本色值
    T_TABS_PRODUCT_COLOR_TEXT_DEFAULT: '#C5CAE3',
    // 圆角，常用于TAG圆角
    T_TAG_BORDER_RADIUS: '2px',
    // 图例/蓝-5
    T_TAG_COLOR_BLUE_BG_DARK: '#70a6ec',
    // 图例/蓝-1
    T_TAG_COLOR_BLUE_BG_LIGHT: '#15253b',
    // 图例/蓝-2
    T_TAG_COLOR_BLUE_BORDER: '#29476d',
    // 紧凑模式下分割线
    T_TAG_COLOR_BLUE_DIVIDER: '#29476d',
    // 图例/蓝-7
    T_TAG_COLOR_BLUE_FILLBG_DARK: '#a1c3ef',
    // 图例/蓝-6
    T_TAG_COLOR_BLUE_FILLBG_LIGHT: '#90bcf6',
    // 内置icon/蓝-5
    T_TAG_COLOR_BLUE_ICON: '#70a6ec',
    // 图例/蓝-5
    T_TAG_COLOR_BLUE_TEXT: '#70a6ec',
    // 图例/青-5
    T_TAG_COLOR_CYAN_BG_DARK: '#3eaa95',
    // 图例/青-1
    T_TAG_COLOR_CYAN_BG_LIGHT: '#1d2c29',
    // 图例/青-2
    T_TAG_COLOR_CYAN_BORDER: '#1e3c37',
    // 紧凑模式下分割线
    T_TAG_COLOR_CYAN_DIVIDER: '#1e3c37',
    // 图例/青-7
    T_TAG_COLOR_CYAN_FILLBG_DARK: '#6de3d1',
    // 图例/青-6
    T_TAG_COLOR_CYAN_FILLBG_LIGHT: '#4ed9bd',
    // 内置icon/青-5
    T_TAG_COLOR_CYAN_ICON: '#3eaa95',
    // 图例/青-5
    T_TAG_COLOR_CYAN_TEXT: '#3eaa95',
    // 标签背景/禁用
    T_TAG_COLOR_DISABLED_BG_DARK: '#f7f7f7',
    // 标签背景/禁用
    T_TAG_COLOR_DISABLED_BG_LIGHT: '#f7f7f7',
    // 标签边框/透明
    T_TAG_COLOR_DISABLED_BORDER: '#2B313F',
    // 紧凑模式下分割线
    T_TAG_COLOR_DISABLED_DIVIDER: '#d9d9d9',
    // 内置icon/禁用
    T_TAG_COLOR_DISABLED_ICON: '#cccccc',
    // 文本/禁用
    T_TAG_COLOR_DISABLED_TEXT: '#535763',
    // 背景/提示状态/深色
    T_TAG_COLOR_GRAY_BG_DARK: '#C5CAE3',
    // 背景/提示状态/浅色
    T_TAG_COLOR_GRAY_BG_LIGHT: '#0B1224',
    // 标签边框/亮
    T_TAG_COLOR_GRAY_BORDER: '#2B3555',
    // 紧凑模式下分割线
    T_TAG_COLOR_GRAY_DIVIDER: '#2B3555',
    // 内置icon/黑色
    T_TAG_COLOR_GRAY_ICON: '#C5CAE3',
    // 标签文案/黑色
    T_TAG_COLOR_GRAY_TEXT: '#C5CAE3',
    // 背景/成功状态/深色
    T_TAG_COLOR_GREEN_BG_DARK: '#2b9f56',
    // 背景/成功状态/浅色
    T_TAG_COLOR_GREEN_BG_LIGHT: '#1e3019',
    // 线条/正确/浅色
    T_TAG_COLOR_GREEN_BORDER: '#236019',
    // 紧凑模式下分割线
    T_TAG_COLOR_GREEN_DIVIDER: '#236019',
    // 内置icon/正确
    T_TAG_COLOR_GREEN_ICON: '#2b9f56',
    // 文本/正确
    T_TAG_COLOR_GREEN_TEXT: '#2b9f56',
    // 图例/浅蓝-5
    T_TAG_COLOR_LIGHTBLUE_BG_DARK: '#399bb0',
    // 图例/浅蓝-1
    T_TAG_COLOR_LIGHTBLUE_BG_LIGHT: '#1c252d',
    // 图例/浅蓝-2
    T_TAG_COLOR_LIGHTBLUE_BORDER: '#1a2f37',
    // 紧凑模式下分割线
    T_TAG_COLOR_LIGHTBLUE_DIVIDER: '#1a2f37',
    // 图例/浅蓝-7
    T_TAG_COLOR_LIGHTBLUE_FILLBG_DARK: '#67cde9',
    // 图例/浅蓝-6
    T_TAG_COLOR_LIGHTBLUE_FILLBG_LIGHT: '#47c7e1',
    // 内置icon/浅蓝-5
    T_TAG_COLOR_LIGHTBLUE_ICON: '#399bb0',
    // 图例/浅蓝-5
    T_TAG_COLOR_LIGHTBLUE_TEXT: '#399bb0',
    // 图例/橙-5
    T_TAG_COLOR_ORANGE_BG_DARK: '#b86d31',
    // 图例/橙-1
    T_TAG_COLOR_ORANGE_BG_LIGHT: '#2e231b',
    // 图例/橙-2
    T_TAG_COLOR_ORANGE_BORDER: '#402c1a',
    // 紧凑模式下分割线
    T_TAG_COLOR_ORANGE_DIVIDER: '#402c1a',
    // 图例/橙-7
    T_TAG_COLOR_ORANGE_FILLBG_DARK: '#f2a65f',
    // 图例/橙-6
    T_TAG_COLOR_ORANGE_FILLBG_LIGHT: '#eb883d',
    // 内置icon/橙-5
    T_TAG_COLOR_ORANGE_ICON: '#b86d31',
    // 图例/橙-5
    T_TAG_COLOR_ORANGE_TEXT: '#b86d31',
    // 背景/纯色/品牌色2
    T_TAG_COLOR_PRIMARY_BG_DARK: '#738BFF',
    // 背景/纯色/品牌色1
    T_TAG_COLOR_PRIMARY_BG_LIGHT: '#5A76FF',
    // 线条/主色
    T_TAG_COLOR_PRIMARY_BORDER: '#5A76FF',
    // 紧凑模式下分割线
    T_TAG_COLOR_PRIMARY_DIVIDER: '#5A76FF',
    // 内置icon/系统白色文本
    T_TAG_COLOR_PRIMARY_ICON: '#ffffff',
    // 系统白色文本
    T_TAG_COLOR_PRIMARY_TEXT: '#ffffff',
    // 图例/紫-5
    T_TAG_COLOR_PURPLE_BG_DARK: '#b186dc',
    // 图例/紫-1
    T_TAG_COLOR_PURPLE_BG_LIGHT: '#2b1d39',
    // 图例/紫-2
    T_TAG_COLOR_PURPLE_BORDER: '#4d3465',
    // 紧凑模式下分割线
    T_TAG_COLOR_PURPLE_DIVIDER: '#4d3465',
    // 图例/紫-7
    T_TAG_COLOR_PURPLE_FILLBG_DARK: '#d5b1f9',
    // 图例/紫-6
    T_TAG_COLOR_PURPLE_FILLBG_LIGHT: '#c499ef',
    // 内置icon/紫-5
    T_TAG_COLOR_PURPLE_ICON: '#b186dc',
    // 图例/紫-5
    T_TAG_COLOR_PURPLE_TEXT: '#b186dc',
    // 背景/错误状态/深色
    T_TAG_COLOR_RED_BG_DARK: '#db3f3f',
    // 背景/错误状态/浅色
    T_TAG_COLOR_RED_BG_LIGHT: '#2e1b1e',
    // 线条/错误/浅色
    T_TAG_COLOR_RED_BORDER: '#6a2e2b',
    // 紧凑模式下分割线
    T_TAG_COLOR_RED_DIVIDER: '#6a2e2b',
    // 图例/红-7
    T_TAG_COLOR_RED_FILLBG_DARK: '#e75f5f',
    // 图例/红-6
    T_TAG_COLOR_RED_FILLBG_LIGHT: '#db3f3f',
    // 内置icon/错误
    T_TAG_COLOR_RED_ICON: '#db3f3f',
    // 文本/错误
    T_TAG_COLOR_RED_TEXT: '#db3f3f',
    // 背景/警告状态/深色
    T_TAG_COLOR_YELLOW_BG_DARK: '#ebb73d',
    // 背景/警告状态/浅色
    T_TAG_COLOR_YELLOW_BG_LIGHT: '#2e281b',
    // 线条/警告/浅色
    T_TAG_COLOR_YELLOW_BORDER: '#51441a',
    // 紧凑模式下分割线
    T_TAG_COLOR_YELLOW_DIVIDER: '#51441a',
    // 图例/黄-7
    T_TAG_COLOR_YELLOW_FILLBG_DARK: '#f2cd5f',
    // 图例/黄-6
    T_TAG_COLOR_YELLOW_FILLBG_LIGHT: '#ebb73d',
    // 内置icon/警告
    T_TAG_COLOR_YELLOW_ICON: '#ebb73d',
    // 文本/警告
    T_TAG_COLOR_YELLOW_TEXT: '#ebb73d',
    // 大号控件高度
    T_TAG_HEIGHT_LG: '28px',
    // 中号控件高度
    T_TAG_HEIGHT_MD: '24px',
    // 小号控件高度
    T_TAG_HEIGHT_SM: '20px',
    // icon最小宽度
    T_TAG_ICON_CLOSE: '#ffffff',
    // 标签关闭按钮/透明度
    T_TAG_ICON_OPACITY_DEFAULT: '1',
    // 标签关闭按钮/透明度/hover
    T_TAG_ICON_OPACITY_HOVER: '1',
    // Tag大号icon
    T_TAG_ICON_SIZE_LG: '14px',
    // Tag中号icon
    T_TAG_ICON_SIZE_MD: '12px',
    // Tag小号icon
    T_TAG_ICON_SIZE_SM: '10px',
    // Tag小号icon
    T_TAG_ICON_SIZE_XS: '6px',
    // icon最小宽度
    T_TAG_ICON_WIDTH_SM: '10px',
    // 粗体字
    T_TYPOGRAPHY_FONT_H1_FONT_WEIGHT: '600',
    // 宽松的行高，字号1.7倍
    T_TYPOGRAPHY_FONT_H1_LINE_HEIGHT: '1.7',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPOGRAPHY_FONT_H1_SIZE: '24px',
    // 粗体字
    T_TYPOGRAPHY_FONT_H2_FONT_WEIGHT: '600',
    // 宽松的行高，字号1.7倍
    T_TYPOGRAPHY_FONT_H2_LINE_HEIGHT: '1.7',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPOGRAPHY_FONT_H2_SIZE: '20px',
    // 粗体字
    T_TYPOGRAPHY_FONT_H3_FONT_WEIGHT: '600',
    // 宽松的行高，字号1.7倍
    T_TYPOGRAPHY_FONT_H3_LINE_HEIGHT: '1.7',
    // 一般用于标题
    T_TYPOGRAPHY_FONT_H3_SIZE: '16px',
    // 粗体字
    T_TYPOGRAPHY_FONT_H4_FONT_WEIGHT: '600',
    // 宽松的行高，字号1.7倍
    T_TYPOGRAPHY_FONT_H4_LINE_HEIGHT: '1.7',
    // 一般用于正文或者小标题
    T_TYPOGRAPHY_FONT_H4_SIZE: '14px',
    // 粗体字
    T_TYPOGRAPHY_FONT_H5_FONT_WEIGHT: '600',
    // 宽松的行高，字号1.7倍
    T_TYPOGRAPHY_FONT_H5_LINE_HEIGHT: '1.7',
    // 一般用于备注/正文，是浏览器识别的最小字号
    T_TYPOGRAPHY_FONT_H5_SIZE: '12px',
    // 默认字体粗细，常规
    T_TYPOGRAPHY_FONT_PARAGRAPH_IMPACT_FONT_WEIGHT: '400',
    // 宽松的行高，字号1.7倍
    T_TYPOGRAPHY_FONT_PARAGRAPH_IMPACT_LINE_HEIGHT: '1.3',
    // 一般用于备注/正文，是浏览器识别的最小字号
    T_TYPOGRAPHY_FONT_PARAGRAPH_IMPACT_SIZE: '12px',
    // 默认字体粗细，常规
    T_TYPOGRAPHY_FONT_PARAGRAPH_NORMAL_FONT_WEIGHT: '400',
    // 宽松的行高，字号1.7倍
    T_TYPOGRAPHY_FONT_PARAGRAPH_NORMAL_LINE_HEIGHT: '1.7',
    // 一般用于备注/正文，是浏览器识别的最小字号
    T_TYPOGRAPHY_FONT_PARAGRAPH_NORMAL_SIZE: '12px',
    // 默认字体粗细，常规
    T_TYPOGRAPHY_FONT_TEXT_FONT_WEIGHT: '400',
    // 宽松的行高，字号1.7倍
    T_TYPOGRAPHY_FONT_TEXT_LINE_HEIGHT: '1.7',
    // 一般用于备注/正文，是浏览器识别的最小字号
    T_TYPOGRAPHY_FONT_TEXT_SIZE: '12px',
    // 排版link中icon的默认颜色
    T_TYPOGRAPHY_ICON_LINK_DEFAULT: '#3F4A70',
    // 排版link中icon的hover颜色
    T_TYPOGRAPHY_ICON_LINK_HOVER: '#738BFF',
    // 一般用于备注/正文，是浏览器识别的最小字号
    T_TYPO_FONT_SIZE_1: '12px',
    // 一般用于正文或者小标题
    T_TYPO_FONT_SIZE_2: '14px',
    // 一般用于标题
    T_TYPO_FONT_SIZE_3: '16px',
    // 一般用于数字
    T_TYPO_FONT_SIZE_4: '18px',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPO_FONT_SIZE_5: '20px',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPO_FONT_SIZE_6: '24px',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPO_FONT_SIZE_7: '28px',
    // 一般用于标题，或者特殊场景下的文本展示
    T_TYPO_FONT_SIZE_8: '32px',
    // 粗体字
    T_TYPO_FONT_WEIGHT_BOLD: '600',
    // 细体字
    T_TYPO_FONT_WEIGHT_LIGHT: '300',
    // 默认字体粗细，常规
    T_TYPO_FONT_WEIGHT_NORMAL: '400',
    // 宽松的行高，字号1.7倍
    T_TYPO_LINE_HEIGHT_LG: '1.7',
    // 中等的行高，字号1.5倍
    T_TYPO_LINE_HEIGHT_MD: '1.5',
    // 密集的行高，字号1.3倍
    T_TYPO_LINE_HEIGHT_SM: '1.3',
    // 大号控件宽度
    T_WIDTH_LG: '320px',
    // 中号控件宽度
    T_WIDTH_MD: '192px',
    // 小号控件宽度
    T_WIDTH_SM: '144px'
};
